import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Transit Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50 flex flex-col items-center`}
      >
        <div className="w-full max-w-md bg-white shadow-lg rounded-xl mt-8 mb-8">
          <header className="px-8 py-6 bg-gradient-to-r from-cyan-500 to-emerald-500 rounded-t-xl shadow-md">
            <h1>
              <Link className="text-white text-2xl font-extrabold tracking-tight" href="/">
                Transit Planner
              </Link>
            </h1>
          </header>
          <main>
            {children}
          </main>
          <footer>

          </footer>
        </div>
      </body>
    </html>
  );
}
